version: '3.8'

services:
  # Python FastAPI Backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - PRODUCT_SERVICE_URL=http://product-service:8080
    volumes:
      - ./backend:/app
    depends_on:
      - product-service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Java Spring Boot Product Service
  product-service:
    build: ./product-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  # React Frontend (for production deployment)
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend